import type { Activity, History } from "@/lib/api";

const WIDTH=900, HEIGHT=270, LEFT=42, TOP=16, BOTTOM=42;
const plotHeight=HEIGHT-TOP-BOTTOM;

export function ActivityChart({data}:{data:Activity[]}){
  const max=Math.max(1,...data.flatMap((point)=>[point.commits,point.merged_prs,point.issues_closed]));
  const step=(WIDTH-LEFT-18)/Math.max(data.length,1); const bar=Math.max(2,Math.min(12,step/4));
  return <ChartFrame legend={[['#c7ff00','Human commits'],['#f1f4ec','Merged PRs'],['#9ba399','Issues closed']]}>{[0,.25,.5,.75,1].map((ratio)=><g key={ratio}><line x1={LEFT} x2={WIDTH-10} y1={TOP+plotHeight*(1-ratio)} y2={TOP+plotHeight*(1-ratio)} stroke="#343a34" strokeDasharray="2 4"/><text x={LEFT-8} y={TOP+plotHeight*(1-ratio)+3} textAnchor="end" fontSize="9" fill="#9ba399">{Math.round(max*ratio)}</text></g>)}{data.map((point,index)=>{const x=LEFT+index*step+step/2;const bars:[[number,string,number],[number,string,number],[number,string,number]]=[[point.commits,"#c7ff00",-bar],[point.merged_prs,"#f1f4ec",0],[point.issues_closed,"#9ba399",bar]];return <g key={point.period}><title>{`${new Date(point.period).toLocaleDateString()}: ${point.commits} commits, ${point.merged_prs} merged PRs, ${point.issues_closed} issues closed`}</title>{bars.map(([value,color,offset],barIndex)=>{const h=value/max*plotHeight;return <rect key={barIndex} x={x+offset-bar/2} y={TOP+plotHeight-h} width={bar} height={h} rx="1" fill={color}/>})}{index%Math.ceil(data.length/6)===0&&<text x={x} y={HEIGHT-24} textAnchor="middle" fontSize="9" fill="#9ba399">{new Date(point.period).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</text>}</g>})}</ChartFrame>;
}

export function StarChart({data}:{data:History[]}){
  const min=Math.min(...data.map((point)=>point.stars));const max=Math.max(...data.map((point)=>point.stars));const range=Math.max(1,max-min);const step=(WIDTH-LEFT-18)/Math.max(data.length-1,1);const points=data.map((point,index)=>`${LEFT+index*step},${TOP+plotHeight-(point.stars-min)/range*plotHeight}`).join(' ');const area=`${LEFT},${TOP+plotHeight} ${points} ${LEFT+(data.length-1)*step},${TOP+plotHeight}`;
  return <ChartFrame legend={[['#c7ff00','Observed stars']]}>{[0,.5,1].map((ratio)=><g key={ratio}><line x1={LEFT} x2={WIDTH-10} y1={TOP+plotHeight*(1-ratio)} y2={TOP+plotHeight*(1-ratio)} stroke="#343a34" strokeDasharray="2 4"/><text x={LEFT-8} y={TOP+plotHeight*(1-ratio)+3} textAnchor="end" fontSize="9" fill="#9ba399">{Intl.NumberFormat('en',{notation:'compact'}).format(min+range*ratio)}</text></g>)}<polygon points={area} fill="#c7ff00" opacity=".1"/><polyline points={points} fill="none" stroke="#c7ff00" strokeWidth="2.5"/>{data.map((point,index)=><circle key={point.captured_at} cx={LEFT+index*step} cy={TOP+plotHeight-(point.stars-min)/range*plotHeight} r="3" fill="#c7ff00"><title>{`${new Date(point.captured_at).toLocaleDateString()}: ${point.stars.toLocaleString()} stars`}</title></circle>)}</ChartFrame>;
}

export function ComparisonActivityChart({leftName,rightName,left,right}:{leftName:string;rightName:string;left:Activity[];right:Activity[]}){
  const leftMap=new Map(left.map((point)=>[new Date(point.period).toISOString().slice(0,10),point.commits]));const rightMap=new Map(right.map((point)=>[new Date(point.period).toISOString().slice(0,10),point.commits]));const dates=Array.from(new Set([...leftMap.keys(),...rightMap.keys()])).sort();const max=Math.max(1,...leftMap.values(),...rightMap.values());const step=(WIDTH-LEFT-18)/Math.max(dates.length-1,1);const line=(values:Map<string,number>)=>dates.map((date,index)=>`${LEFT+index*step},${TOP+plotHeight-(values.get(date)??0)/max*plotHeight}`).join(' ');
  return <ChartFrame legend={[['#c7ff00',leftName],['#f1f4ec',rightName]]}>{[0,.5,1].map((ratio)=><g key={ratio}><line x1={LEFT} x2={WIDTH-10} y1={TOP+plotHeight*(1-ratio)} y2={TOP+plotHeight*(1-ratio)} stroke="#343a34" strokeDasharray="2 4"/><text x={LEFT-8} y={TOP+plotHeight*(1-ratio)+3} textAnchor="end" fontSize="9" fill="#9ba399">{Math.round(max*ratio)}</text></g>)}<polyline points={line(leftMap)} fill="none" stroke="#c7ff00" strokeWidth="2.5"/><polyline points={line(rightMap)} fill="none" stroke="#f1f4ec" strokeWidth="2.5"/>{dates.map((date,index)=>index%Math.ceil(dates.length/6)===0&&<text key={date} x={LEFT+index*step} y={HEIGHT-24} textAnchor="middle" fontSize="9" fill="#9ba399">{new Date(date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</text>)}</ChartFrame>;
}

function ChartFrame({children,legend}:{children:React.ReactNode;legend:Array<[string,string]>}){return <div className="w-full"><svg role="img" viewBox={`0 0 ${WIDTH} ${HEIGHT}`} className="h-auto w-full overflow-visible">{children}</svg><div className="mt-1 flex flex-wrap justify-center gap-5">{legend.map(([color,label])=><span key={label} className="inline-flex items-center gap-1.5 text-[10px] text-[#9ba399]"><span className="size-2 rounded-sm" style={{backgroundColor:color}}/>{label}</span>)}</div></div>}
