"use client";

import { ClipboardDocumentIcon, PlusIcon, XMarkIcon } from "@heroicons/react/20/solid";
import { useState } from "react";

export function IngestionCommand() {
  const [open,setOpen]=useState(false);const [repository,setRepository]=useState("owner/repository");const command=`python -m app.cli ingest ${repository || "owner/repository"}`;
  return <><button onClick={()=>setOpen(true)} className="button-primary"><PlusIcon className="size-4"/>Add repository</button>{open&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-[100] grid place-items-center bg-[#080a08]/55 p-4" onMouseDown={()=>setOpen(false)}><div className="w-full max-w-lg rounded-lg border border-[#343a34] bg-[#101310] shadow-2xl" onMouseDown={(event)=>event.stopPropagation()}><div className="flex items-center justify-between border-b border-[#343a34] px-5 py-4"><div><h2 className="text-sm font-semibold">Add repository evidence</h2><p className="mt-1 text-xs text-[#9ba399]">Ingestion remains an explicit backend operation.</p></div><button onClick={()=>setOpen(false)} className="rounded p-1 text-[#9ba399] hover:bg-[#171b17]"><XMarkIcon className="size-5"/></button></div><div className="p-5"><label className="data-label">GitHub repository<input value={repository} onFocus={()=>repository==="owner/repository"&&setRepository("")} onChange={(event)=>setRepository(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-[#343a34] px-3 font-mono text-xs text-[#f1f4ec]"/></label><p className="mt-4 text-xs leading-5 text-[#9ba399]">From the activated backend virtual environment, run:</p><div className="mt-2 flex items-center gap-2 rounded-md bg-[#080a08] p-3"><code className="min-w-0 flex-1 overflow-x-auto whitespace-nowrap text-xs text-slate-100">{command}</code><button onClick={()=>navigator.clipboard.writeText(command)} title="Copy command" className="text-slate-300 hover:text-[#f1f4ec]"><ClipboardDocumentIcon className="size-4"/></button></div><p className="mt-4 rounded-md bg-[#101310] p-3 text-[11px] leading-4 text-[#b9c0b7]">The first run collects available history. Later runs are incremental and add the snapshots needed for real growth rates.</p></div></div></div>}</>;
}
