import { ArrowLeftIcon, ArrowTopRightOnSquareIcon, ClockIcon } from "@heroicons/react/20/solid";
import Link from "next/link";

import { ActivityChart, StarChart } from "@/components/charts";
import { EmptyState, EvidenceItem, ScoreBar, SectionHeader, StatusBadge, WindowControl } from "@/components/ui";
import { api, type Activity, type Contributor, type History, type Metric, type Repo } from "@/lib/api";
import { assessment, compact, duration, getNumber, percent, relativeDate } from "@/lib/format";

export default async function RepositoryPage({ params, searchParams }: { params: Promise<{ owner: string; repo: string }>; searchParams: Promise<{ window?: string }> }) {
  const { owner, repo } = await params;
  const requested = Number((await searchParams).window ?? 30);
  const window = [30, 90, 365].includes(requested) ? requested : 30;
  let repository: Repo; let metrics: Metric; let activity: Activity[]; let history: History[]; let contributors: Contributor[];
  try { [repository, metrics, activity, history, contributors] = await Promise.all([api.repo(owner, repo), api.metrics(owner, repo, window), api.activity(owner, repo, window === 365 ? 52 : window === 90 ? 24 : 12), api.history(owner, repo), api.contributors(owner, repo)]); }
  catch { return <main><div className="mx-auto max-w-[1100px] px-5 py-16"><EmptyState title={`No analysis for ${owner}/${repo}`} description="Confirm the API is running and that this repository completed ingestion." /></div></main>; }
  const state = assessment(metrics);
  const confidence = getNumber(metrics, "data_quality", "confidence_score");
  const topShare = getNumber(metrics, "concentration", "top_1_share");
  const commitChange = getNumber(metrics, "velocity", "commit_change");
  const historyAvailable = metrics.components?.growth?.history_available === true;

  return <main><header className="border-b border-[#343a34] bg-[#101310]"><div className="mx-auto max-w-[1440px] px-5 py-6 md:px-8 xl:px-10"><div className="flex items-center justify-between gap-4"><Link href="/repositories" className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#9ba399] hover:text-[#f1f4ec]"><ArrowLeftIcon className="size-3.5" />Repository directory</Link><WindowControl active={window} /></div><div className="mt-6 flex flex-wrap items-start justify-between gap-6"><div className="max-w-3xl"><div className="flex flex-wrap items-center gap-3"><h1 className="display-face break-all text-[clamp(34px,4vw,64px)] leading-none tracking-[-0.035em]">{repository.full_name}</h1><StatusBadge status={state.status} tone={state.tone} />{repository.archived && <StatusBadge status="Archived" tone="critical" />}</div><p className="mt-3 text-sm leading-6 text-[#9ba399]">{repository.description || "No repository description provided."}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#9ba399]"><span>{repository.primary_language ?? "Language unknown"}</span><span>{repository.license ?? "No license detected"}</span><span>Default: {repository.default_branch}</span><a href={`https://github.com/${repository.full_name}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold text-[#c7ff00]">Open on GitHub <ArrowTopRightOnSquareIcon className="size-3" /></a></div></div><div className="grid grid-cols-3 gap-7"><HeaderStat label="Stars" value={compact(repository.stars)} /><HeaderStat label="Forks" value={compact(repository.forks)} /><HeaderStat label="Open items" value={compact(repository.open_issues)} /></div></div></div></header>
    <div className="mx-auto max-w-[1440px] space-y-6 px-5 py-6 md:px-8 xl:px-10">
      <section className="grid gap-4 lg:grid-cols-[1.1fr_repeat(3,minmax(0,1fr))]"><div className="hairline-grid border border-[#697168] bg-[#080a08] p-5 text-[#f1f4ec]"><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-slate-400">Research view</p><h2 className="mt-3 text-lg font-semibold leading-6">{assessmentSentence(repository,metrics)}</h2><div className="mt-5 flex items-center gap-2 text-[11px] text-slate-400"><ClockIcon className="size-3.5" />Data synced {relativeDate(repository.last_ingested_at)} · confidence {Math.round(confidence ?? 0)}%</div></div><ScorePanel label="Momentum" value={metrics.momentum_score} note="Growth and acceleration" /><ScorePanel label="Community health" value={metrics.health_score} note="Response and delivery" tone="green" /><ScorePanel label="Concentration risk" value={metrics.bus_factor_risk} note="Human commit dependency" tone={(metrics.bus_factor_risk ?? 0) >= 70 ? "red" : "amber"} /></section>

      <section className="grid overflow-hidden rounded-lg border border-[#343a34] bg-[#101310] md:grid-cols-2 xl:grid-cols-4"><Question label="Actively maintained?" answer={(getNumber(metrics,"freshness","days_since_commit") ?? 999) <= 30 ? "Yes" : "Needs review"} evidence={`${compact(getNumber(metrics,"velocity","commits"))} human commits · ${relativeDate(metrics.components?.freshness?.last_commit_at)}`} positive={(getNumber(metrics,"freshness","days_since_commit") ?? 999) <= 30}/><Question label="Community responsive?" answer={getNumber(metrics,"responsiveness","median_pr_merge_hours") == null ? "Insufficient evidence" : duration(getNumber(metrics,"responsiveness","median_pr_merge_hours"))} evidence={`Median PR merge cycle · n=${getNumber(metrics,"responsiveness","merged_pr_sample_size") ?? 0}`} positive={(getNumber(metrics,"responsiveness","median_pr_merge_hours") ?? 999) < 168}/><Question label="Adoption growing?" answer={historyAvailable ? percent(getNumber(metrics,"growth","star_rate"),true) : "Building baseline"} evidence={historyAvailable ? `${window}-day observed star change` : "A second historical observation is required"} positive={historyAvailable && (getNumber(metrics,"growth","star_rate") ?? 0) > 0}/><Question label="Contributor-resilient?" answer={(metrics.bus_factor_risk ?? 100) < 50 ? "Distributed" : "Concentrated"} evidence={topShare == null ? "No contribution evidence" : `Top author share ${percent(topShare)}`} positive={(metrics.bus_factor_risk ?? 100) < 50}/></section>

      <section className="grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,.55fr)]"><div className="panel overflow-hidden"><SectionHeader title="Development activity" description="Weekly human commits, merged pull requests, and closed issues." /><div className="p-4"><ActivityChart data={activity} /></div></div><div className="panel overflow-hidden"><SectionHeader title="Delivery operations" description={`${window}-day resolved-event view.`}/><div className="divide-y divide-[#343a34]"><Operation label="Human commits" value={compact(getNumber(metrics,"velocity","commits"))} change={commitChange}/><Operation label="Automation share" value={percent(getNumber(metrics,"velocity","automation_share"))}/><Operation label="Pull requests opened" value={compact(getNumber(metrics,"velocity","pull_requests"))} change={getNumber(metrics,"velocity","pr_change")}/><Operation label="Pull requests merged" value={compact(getNumber(metrics,"velocity","merged_pull_requests"))}/><Operation label="Issues opened / closed" value={`${compact(getNumber(metrics,"velocity","issues_opened"))} / ${compact(getNumber(metrics,"velocity","issues_closed"))}`}/><Operation label="Stable releases" value={compact(getNumber(metrics,"velocity","releases"))}/></div></div></section>

      <section className="grid gap-6 xl:grid-cols-[minmax(0,1.15fr)_minmax(340px,.85fr)]"><div className="panel overflow-hidden"><SectionHeader title="Observed star trajectory" description="Point-in-time snapshots only; historical values are never reconstructed." /><div className="p-4">{history.length > 1 ? <StarChart data={history}/> : <div className="grid h-[300px] place-items-center text-center"><div><p className="text-sm font-semibold">Baseline established</p><p className="mt-2 max-w-sm text-xs leading-5 text-[#9ba399]">Run ingestion again later to turn this observation into an actual growth trajectory.</p></div></div>}</div></div><div className="panel overflow-hidden"><SectionHeader title="Signal ledger" description="Evidence helping or hurting the assessment."/><div className="px-5">{repositoryLedger(repository,metrics).map((item,index)=><EvidenceItem key={index} {...item}/>)}</div></div></section>

      <section className="grid gap-6 xl:grid-cols-2"><div className="panel overflow-hidden"><SectionHeader title="Contribution distribution" description="GitHub-reported cumulative contribution totals; recent score calculations exclude known bots."/><div className="p-5"><ContributorDistribution contributors={contributors.slice(0,8)}/></div></div><div className="panel overflow-hidden"><SectionHeader title="Score drivers" description="Normalized components behind the two composite scores."/><div className="grid gap-6 p-5 sm:grid-cols-2"><DriverGroup title="Momentum" values={metrics.components?.momentum ?? {}}/><DriverGroup title="Community health" values={metrics.components?.health ?? {}}/></div></div></section>

      <section className="panel overflow-hidden"><SectionHeader title="Evidence quality" description="Precision is bounded by event samples and snapshot history."/><div className="grid divide-y divide-[#343a34] sm:grid-cols-4 sm:divide-x sm:divide-y-0"><Quality label="Confidence" value={`${Math.round(confidence ?? 0)}%`}/><Quality label="Events in window" value={compact(getNumber(metrics,"data_quality","event_count"))}/><Quality label="Historical snapshots" value={compact(getNumber(metrics,"data_quality","snapshot_count"))}/><Quality label="Snapshot coverage" value={`${getNumber(metrics,"data_quality","snapshot_span_days")?.toFixed(0) ?? 0} days`}/></div></section>
    </div>
  </main>;
}

function HeaderStat({label,value}:{label:string;value:string}){return <div><span className="data-label block">{label}</span><b className="mt-1 block font-mono text-lg">{value}</b></div>}
function ScorePanel({label,value,note,tone="blue"}:{label:string;value:number|null;note:string;tone?:"blue"|"green"|"amber"|"red"}){return <div className="panel p-5"><p className="data-label">{label}</p><div className="mt-5"><ScoreBar value={value} tone={tone}/></div><p className="mt-4 text-[11px] text-[#70776f]">{note}</p></div>}
function Question({label,answer,evidence,positive}:{label:string;answer:string;evidence:string;positive:boolean}){return <div className="border-b border-[#343a34] p-5 last:border-0 md:border-r xl:border-b-0"><p className="data-label">{label}</p><p className={`mt-2 text-base font-semibold ${positive?"text-[#c7ff00]":"text-[#f1f4ec]"}`}>{answer}</p><p className="mt-2 text-[11px] leading-4 text-[#9ba399]">{evidence}</p></div>}
function Operation({label,value,change}:{label:string;value:string;change?:number|null}){return <div className="flex items-center justify-between gap-4 px-5 py-3.5"><span className="text-xs text-[#9ba399]">{label}</span><div className="text-right"><b className="font-mono text-xs">{value}</b>{change!=null&&<span className={`ml-2 text-[10px] font-semibold ${change>=0?"text-[#c7ff00]":"text-[#f1f4ec]"}`}>{change>=0?"+":""}{(change*100).toFixed(0)}%</span>}</div></div>}
function ContributorDistribution({contributors}:{contributors:Contributor[]}){const total=contributors.reduce((sum,item)=>sum+item.contributions,0);return <div className="space-y-3">{contributors.map((item,index)=><div key={item.login} className="grid grid-cols-[24px_120px_1fr_52px] items-center gap-3"><span className="font-mono text-[10px] text-[#70776f]">{String(index+1).padStart(2,"0")}</span><span className="truncate text-xs font-medium">{item.login}</span><div className="h-1.5 overflow-hidden rounded-full bg-[#343a34]"><div className="h-full bg-[#c7ff00]" style={{width:`${item.contributions/Math.max(total,1)*100}%`}}/></div><span className="text-right font-mono text-[10px]">{compact(item.contributions)}</span></div>)}</div>}
function DriverGroup({title,values}:{title:string;values:Record<string,number>}){return <div><h3 className="text-xs font-semibold">{title}</h3><div className="mt-3 space-y-3">{Object.entries(values).map(([key,value])=><div key={key}><div className="flex justify-between gap-4 text-[11px]"><span className="capitalize text-[#9ba399]">{key.replaceAll("_"," ")}</span><b className="font-mono">{Math.round(value)}</b></div><div className="mt-1 h-1 overflow-hidden rounded-full bg-[#343a34]"><div className="h-full bg-[#c7ff00]" style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div>)}</div></div>}
function Quality({label,value}:{label:string;value:string}){return <div className="p-5"><p className="data-label">{label}</p><p className="mt-2 font-mono text-lg font-semibold">{value}</p></div>}

function assessmentSentence(repository:Repo,metric:Metric):string{const state=assessment(metric);const commits=getNumber(metric,"velocity","commits")??0;const risk=metric.bus_factor_risk??0;if(repository.archived)return "Archived repository; historical evidence remains available for comparison.";if(commits===0)return "No recent human commit activity is recorded in this window.";if(risk>=70)return `${state.status} delivery profile, with material dependence on a small contributor set.`;if((metric.health_score??0)>=65)return `${state.status} trajectory with healthy delivery and community evidence.`;return `${state.status} trajectory; review the evidence ledger before drawing a conclusion.`}
function repositoryLedger(repository:Repo,metric:Metric):Array<{tone:"positive"|"warning"|"critical"|"neutral";title:string;detail:string}>{const change=getNumber(metric,"velocity","commit_change");const top=getNumber(metric,"concentration","top_1_share");const flow=getNumber(metric,"velocity","net_issue_flow");const data=[] as Array<{tone:"positive"|"warning"|"critical"|"neutral";title:string;detail:string}>;if(change!=null){const flat=Math.abs(change)<.005;data.push({tone:flat?"neutral":change>0?"positive":change<-.25?"critical":"warning",title:flat?"Human commit activity was unchanged":`Human commit activity ${change>0?"increased":"declined"} ${Math.abs(change*100).toFixed(0)}%`,detail:`Compared with the preceding equal ${metric.window_days}-day period; known bot accounts are excluded.`})}if(top!=null)data.push({tone:top>=.65?"critical":top>=.4?"warning":"positive",title:`Top contributor authored ${(top*100).toFixed(0)}% of recent commits`,detail:"Contribution concentration is a dependency proxy, not a literal maintainer bus factor."});if(flow!=null)data.push({tone:flow>=0?"positive":"warning",title:flow>=0?`${flow} more issues closed than opened`:`Issue intake exceeded closures by ${Math.abs(flow)}`,detail:"Net issue flow in the selected analysis window."});if(metric.components?.growth?.history_available!==true)data.push({tone:"neutral",title:"Growth baseline is still forming",detail:"A later ingestion snapshot is required before star and contributor growth can be measured."});return data.slice(0,4)}
